version: "3.7"
volumes:
    node_modules:
services:
    development:
        build: .
        volumes:
            - ..:/workspace
            - ~/.gitconfig:/root/.gitconfig
            - /var/run/docker.sock:/var/run/docker.sock
            - node_modules:/workspace/node_modules/
        ports:
            - 8000:8000
        env_file: ../.env
        command: sleep infinity
